apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: istio-system
spec:
  selfSigned:
    crlDistributionPoints:
      - "http://blog.maytan.me"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-maytan-me
  namespace: istio-system
spec:
  secretName: blog-maytan-me-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - maytan
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - blog.maytan.me
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
