apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
      - name: client-service
        image: maytanthegeek/microservice-client:1.0.0-mesh
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
