openapi: 3.0.3
info:
  title: user-service
  version: 1.0.0
paths:
  /user/{userId}:
    get:
      description: 'Retrieves info about a user.'
      responses:
        '200':
          description: 'Acknowledgement with same message and timestamp.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
              example:
                id: 0
                name: Guest